### ISSUE TITLE
possibly scanning too fast?

### ISSUE THREAD

**Issue by tlundse** [favll/pogom#90]
two accounts scanning, gives this:

2016-08-08 20:37:56,087 [       scan] [   INFO] Completed 15.29% of scan.
2016-08-08 20:38:06,327 [       scan] [   INFO] Completed 16.47% of scan.
2016-08-08 20:38:06,442 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:38:16,691 [       scan] [   INFO] Completed 17.65% of scan.
2016-08-08 20:38:17,412 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:38:27,028 [       scan] [   INFO] Completed 18.82% of scan.
2016-08-08 20:38:28,386 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:38:37,206 [       scan] [   INFO] Completed 20.00% of scan.
2016-08-08 20:38:39,356 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:38:47,407 [       scan] [   INFO] Completed 21.18% of scan.
2016-08-08 20:38:50,327 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:38:57,596 [       scan] [   INFO] Completed 22.35% of scan.
2016-08-08 20:39:01,300 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:07,887 [       scan] [   INFO] Completed 23.53% of scan.
2016-08-08 20:39:12,347 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:18,060 [       scan] [   INFO] Completed 24.71% of scan.
2016-08-08 20:39:23,425 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:28,234 [       scan] [   INFO] Completed 25.88% of scan.
2016-08-08 20:39:34,424 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:38,407 [       scan] [   INFO] Completed 27.06% of scan.
2016-08-08 20:39:45,402 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:48,583 [       scan] [   INFO] Completed 28.24% of scan.
2016-08-08 20:39:56,372 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:39:59,107 [       scan] [   INFO] Completed 29.41% of scan.
2016-08-08 20:40:07,419 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 20:40:10,206 [       scan] [   INFO] Completed 30.59% of scan.
2016-08-08 20:40:18,395 [       scan] [   INFO] Map Download failed. Trying again.

**Comment by Lionir** [comment]
It's a problem with your Google Maps API, I think.

**Comment by tlundse** [comment]
The map seems to be working fine, while zooming and panning in the web browser, at least.

**Comment by nborrmann** [comment]
Interesting. Only one account seems to be affected. We might need to re-login that account.

**Comment by Lionir** [comment]
Well, I'm not a Dev nor an experienced users so I might be wrong but it'd make sense to me.

**Comment by Lionir** [comment]
Does Both Account have the TOS accepted? You might also need to do the tutorial.. But I'm not sure.

**Comment by nborrmann** [comment]
We automatically accept the ToS if they haven't been accepted before, so that's not the problem.

**Comment by tlundse** [comment]
It was hard to restart the server :)

2016-08-08 20:55:42,561 [       scan] [   INFO] Completed 34.12% of scan.
^C^C^C^C^C2016-08-08 20:55:49,625 [       scan] [   INFO] Map Download failed. Trying again.

had to ^Z and then kill %1

**Comment by tlundse** [comment]
restarting solved the issue!

2016-08-08 20:56:09,032 [   auth_ptc] [   INFO] PTC Access Token successfully retrieved.
2016-08-08 20:56:09,095 [   auth_ptc] [   INFO] PTC Access Token successfully retrieved.
2016-08-08 20:56:09,639 [       scan] [   INFO] Completed  1.18% of scan.
2016-08-08 20:56:09,986 [       scan] [   INFO] Completed  2.35% of scan.
2016-08-08 20:56:19,838 [       scan] [   INFO] Completed  3.53% of scan.
2016-08-08 20:56:20,132 [       scan] [   INFO] Completed  4.71% of scan.
2016-08-08 20:56:30,044 [       scan] [   INFO] Completed  5.88% of scan.
2016-08-08 20:56:30,326 [       scan] [   INFO] Completed  7.06% of scan.

**Comment by stlmikey80** [comment]
I get this to..  i notice it when account fails to get token..


2016-08-08 13:57:05,674 [       scan] [   INFO] Completed 58.50% of scan.
2016-08-08 13:57:05,684 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 13:57:05,822 [       scan] [   INFO] Completed 58.56% of scan.
2016-08-08 13:57:05,944 [       scan] [   INFO] Completed 58.61% of scan.
2016-08-08 13:57:06,033 [       scan] [   INFO] Map Download failed. Trying again.
2016-08-08 13:57:06,058 [       scan] [   INFO] Completed 58.67% of scan.
2016-08-08 13:57:06,453 [       scan] [   INFO] Completed 58.73% of scan.
2016-08-08 13:57:06,513 [       scan] [   INFO] Completed 58.78% of scan.
2016-08-08 13:57:06,931 [       scan] [   INFO] Map Download failed. Trying again.

**Comment by favll** [comment]
Where are your hosting your applications? There are several hosting providers whose IP ranges have been blocked by Niantic.

**Comment by nborrmann** [comment]
Should be fixed in 7b6869cf3060a3682ca834335e1ac666f0920e6c. But needs more testing.

**Comment by lax20attack** [comment]
Confirmed still exists with latest. Saw it once for all of my accounts. Slowed sleep from 5 seconds to time.sleep(random.randrange(6,9)) and it hasn't happened again.

**Comment by Lionir** [comment]
@lax20attack Where would I change this?

**Comment by nborrmann** [comment]
Please comment if this still occurs.
